//TAREFAS A FAZER
//GET
export const GET_TAREFAS_A_FAZER = 'GET_TAREFAS_A_FAZER'
export const GET_TAREFAS_A_FAZER_SUCCESS = 'GET_TAREFAS_A_FAZER_SUCCESS'
export const GET_TAREFAS_A_FAZER_FAILURE = 'GET_TAREFAS_A_FAZER_FAILURE'
//ADD
export const ADD_TAREFAS_A_FAZER = 'ADD_TAREFAS_A_FAZER'
export const ADD_TAREFAS_A_FAZER_SUCCESS = 'ADD_TAREFAS_A_FAZER_SUCCESS'
export const ADD_TAREFAS_A_FAZER_FAILURE = 'ADD_TAREFAS_A_FAZER_FAILURE'
//UPDATE
export const UPDATE_TAREFAS_A_FAZER = 'UPDATE_TAREFAS_A_FAZER'
export const UPDATE_TAREFAS_A_FAZER_SUCCESS = 'UPDATE_TAREFAS_A_FAZER_SUCCESS'
export const UPDATE_TAREFAS_A_FAZER_FAILURE = 'UPDATE_TAREFAS_A_FAZER_FAILURE'
//DELETE
export const DELETE_TAREFAS_A_FAZER = 'DELETE_TAREFAS_A_FAZER'
export const DELETE_TAREFAS_A_FAZER_SUCCESS = 'DELETE_TAREFAS_A_FAZER_SUCCESS'
export const DELETE_TAREFAS_A_FAZER_FAILURE = 'DELETE_TAREFAS_A_FAZER_FAILURE'

//TAREFAS SENDO FEITAS
//GET
export const GET_TAREFAS_FAZENDO = 'GET_TAREFAS_FAZENDO'
export const GET_TAREFAS_FAZENDO_SUCCESS = 'GET_TAREFAS_FAZENDO_SUCCESS'
export const GET_TAREFAS_FAZENDO_FAILURE = 'GET_TAREFAS_FAZENDO_FAILURE'
//ADD
export const ADD_TAREFAS_FAZENDO = 'ADD_TAREFAS_FAZENDO'
export const ADD_TAREFAS_FAZENDO_SUCCESS = 'ADD_TAREFAS_FAZENDO_SUCCESS'
export const ADD_TAREFAS_FAZENDO_FAILURE = 'ADD_TAREFAS_FAZENDO_FAILURE'
//UPDATE
export const UPDATE_TAREFAS_FAZENDO = 'UPDATE_TAREFAS_FAZENDO'
export const UPDATE_TAREFAS_FAZENDO_SUCCESS = 'UPDATE_TAREFAS_FAZENDO_SUCCESS'
export const UPDATE_TAREFAS_FAZENDO_FAILURE = 'UPDATE_TAREFAS_FAZENDO_FAILURE'
//DELETE
export const DELETE_TAREFAS_FAZENDO = 'DELETE_TAREFAS_FAZENDO'
export const DELETE_TAREFAS_FAZENDO_SUCCESS = 'DELETE_TAREFAS_FAZENDO_SUCCESS'
export const DELETE_TAREFAS_FAZENDO_FAILURE = 'DELETE_TAREFAS_FAZENDO_FAILURE'

//TAREFAS FEITAS
//GET
export const GET_TAREFAS_FEITAS = 'GET_TAREFAS_FEITAS'
export const GET_TAREFAS_FEITAS_SUCCESS = 'GET_TAREFAS_FEITAS_SUCCESS'
export const GET_TAREFAS_FEITAS_FAILURE = 'GET_TAREFAS_FEITAS_FAILURE'
//ADD
export const ADD_TAREFAS_FEITAS = 'ADD_TAREFAS_FEITAS'
export const ADD_TAREFAS_FEITAS_SUCCESS = 'ADD_TAREFAS_FEITAS_SUCCESS'
export const ADD_TAREFAS_FEITAS_FAILURE = 'ADD_TAREFAS_FEITAS_FAILURE'
//UPDATE
export const UPDATE_TAREFAS_FEITAS = 'UPDATE_TAREFAS_FEITAS'
export const UPDATE_TAREFAS_FEITAS_SUCCESS = 'UPDATE_TAREFAS_FEITAS_SUCCESS'
export const UPDATE_TAREFAS_FEITAS_FAILURE = 'UPDATE_TAREFAS_FEITAS_FAILURE'
//DELETE
export const DELETE_TAREFAS_FEITAS = 'DELETE_TAREFAS_FEITAS'
export const DELETE_TAREFAS_FEITAS_SUCCESS = 'DELETE_TAREFAS_FEITAS_SUCCESS'
export const DELETE_TAREFAS_FEITAS_FAILURE = 'DELETE_TAREFAS_FEITAS_FAILURE'
