//STARTED
export const STARTED = 'STARTED'
//FAILURE
export const FAILED = 'FAILED'
//TAREFAS
export const GET_TAREFAS = 'GET_TAREFAS'
export const SET_TAREFAS = 'SET_TAREFAS'
export const ADD_TAREFA = 'ADD_TAREFA'
export const UPDATE_TAREFA = 'UPDATE_TAREFA'
export const DELETE_TAREFA = 'DELETE_TAREFA'
export const TROCA_STATUS = 'TROCA_STATUS'
